### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by shenjackyuanjie** [slowsage/mdbook-pagetoc#5]
https://github.com/shenjackyuanjie/Difficult-Rocket/actions/runs/4398279637/jobs/7702023860
look's like some issue in os?

(sorry if I'm rude for asking a actions issue

**Comment by shenjackyuanjie** [comment]
BTW
i success after I upload the theme folder to github
https://github.com/shenjackyuanjie/Difficult-Rocket/actions/runs/4398352074/jobs/7702142449

**Comment by slowsage** [comment]
I'm not able to reproduce the issue with your repo @commit 598c3bc.

I just pushed out a new version (v0.1.7) that logs the same way as mdbook - so it should show where it wrote the files in the github actions log if you try again.

If that doesn't work, my suggestion is to get a locally (i.e. not in github actions) reproducible error if you can.

**Comment by shenjackyuanjie** [comment]
got it, thanks!
I'll try it

**Comment by shenjackyuanjie** [comment]
https://github.com/shenjackyuanjie/Difficult-Rocket/actions/runs/4405847243/jobs/7717275521

well. I better just upload the theme folder······

**Comment by shenjackyuanjie** [comment]
also, I can't get a reproducible error at locally

sorry😂
